### ISSUE TITLE
Native click events don't work on ElementMixin components

### ISSUE THREAD

**Issue by Jexordexan** [Jexordexan/vue-slicksort#10]
As noted by @johnfraney in #9:
>in version 0.1.5 that items with the ElementMixin no longer register click events. Maybe the CSS fix is the safer option.

Reverting the earlier commit and replacing with the prefixed css rules is the appropriate fix. I will be adding autoprefixer to the storybook webpack config.

**Comment by Jexordexan** [comment]
Fixed in f18e705cd01edd23cff767f582e037fd9b48b9b4

**Comment by annethereshewent** [comment]
this is still a bug as far as i can tell, do i have to do something special to install the fixed version?
