### ISSUE TITLE
Dragging between lists

### ISSUE THREAD

**Issue by hako-studio** [Jexordexan/vue-slicksort#103]
This is a fantastic project and the ability to drag in a grid is a feature I've not found anywhere else. However, I was wondering if there was a way you could drag and drop between two lists?

I have two arrays and I want to be able to move items between them; is this possible?

Thanks!

**Comment by alandecastros** [comment]
I wanna know this too. 

Regards

**Comment by mgesmundo** [comment]
Me too.
All the best

**Comment by edison1105** [comment]
Me too.
if it can copy one item from A to B is better.

Regards.

**Comment by andygithubchen** [comment]
Me too.
All the best
Regards.

**Comment by P4Thi0ut** [comment]
Relates to [this idea](https://github.com/Jexordexan/vue-slicksort/issues/2)

**Comment by Jexordexan** [comment]
Duplicate of #2
