### ISSUE TITLE
When registering component globally, I get Unknown custom element did you register component correctly

### ISSUE THREAD

**Issue by atlcodecommandr** [Jexordexan/vue-slicksort#116]
Unknown custom element: <SlickList> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Unknown custom element: <SlickItem> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

import { SlickList, SlickItem } from 'vue-slicksort';
Vue.component(SlickList);
Vue.component(SlickItem);

**Comment by Jexordexan** [comment]
You should be giving the components a name as the first argument.

```
Vue.component('slick-list', SlickList)
```
