### ISSUE TITLE
error throw by judge lockoffset

### ISSUE THREAD

**Issue by sally2015** [Jexordexan/vue-slicksort#12]
In the ContainerMinxin.js

> getLockPixelOffset(lockOffset) {    
>  ...
>             if (typeof lockOffset === 'string') {
>                 const match = /^[+-]?\d*(?:\.\d*)?(px|%)$/.exec(lockOffset);
>                 if (match !== null) {
>                     throw new Error(`lockOffset value should be a number or a string of a number followed by "px" or "%". Given ${lockOffset}`);
>                 }

But in my test, when the lockOffset equal '2px',
match is ["2px", "px", index: 0, input: "2px", groups: undefined]
so **match !== null** return true，and throw the error tips，which I think is the mistake;

If that is not the mistake，please tell me what is the principle？Thanks

**Comment by Jexordexan** [comment]
Yup, this is a bug. I incorrectly refactored this code. Thanks for the find!
