### ISSUE TITLE
Source data does not seem to be updated when @sort-end fires

### ISSUE THREAD

**Issue by davestewart** [Jexordexan/vue-slicksort#129]
Hey Jordan,

A bit confused by this one...

I'm using `v-model` as suggested in the docs to update the sortable parent. I'm also using `@sort-end` to report updates so I can save the source data.

However, the data appears to always be one drag behind!

```js
    onSortEnd ({ newIndex, oldIndex }) {
      console.log(this.items.map(item => item.title)) // always one drag behind!
      // can't save items :(
    },
```

Whilst investigating the `v-model` setup, I replaced it with a simple `:value="items"` prop and instead did my own ordering in the sort end handler:

```js
    onSortEnd ({ newIndex, oldIndex }) {
      this.items.splice(newIndex, 0, ...this.items.splice(oldIndex, 1))
      console.log(this.items.map(item => item.title)) // looking good
      // save items :)
    },
```

The manual method works for me, but any idea what is going on?

Is this expected behaviour?

**Comment by Jexordexan** [comment]
Hey, not really sure. can you post a repro and include the version youre working with? That can help with identifying the issue

**Comment by Jexordexan** [comment]
On second glance, it looks like `sort-end` fires right before `input` (which is what causes the v-model to update). Maybe the event you want to listen to is `input`

**Comment by davestewart** [comment]
Hey, thanks for looking at this!

I'll be back on that project tomorrow, so I'll take a look and will report back

👍

**Comment by davestewart** [comment]
Hey,

I just got back to working on this again, and yes - it looks like that was the issue!

It might be worth mentioning this in the docs:

> Fired when sorting has ended. Note that the data has not been updated yet (see @input).

As I mentioned, I'm saving data, so it seemed weird to me to have:

- a v-model (`:value` in, `@input` out) 
- a second *manual* `@input` to report the update.

Not sure why I didn't try it as it is in the docs, right below.

Maybe I saw it and ignored it. Maybe in my head I thought "you can't have two inputs". 

Who knows, but that works now!

Thanks.

**Comment by Jexordexan** [comment]
Yeah, I guess the ordering of `sort-end` and `input` are arbitrary, but I dont plan to change them. You don't have to use `v-model` however, if you just set the model value inside of your `@input` listener, that makes it clear when exactly the value is updated and you can report the update in the same method.

```vue
<slick-list :value="list" @input="onUpdate">...</slick-list>

// ...

onUpdate(newList) {
  this.list = newList
  tellTheWorldIveChanged()
}

```

**Comment by davestewart** [comment]
Yeah, sure. I was just explaining it from the perspective of someone who thought "great! a library to solve my needs! let's plug it in then crack on with the rest of the stuff I have to do...".

Anyway.

Thanks again :D
