### ISSUE TITLE
If dragging element is a canvas, its ghost is not shown when dragging

### ISSUE THREAD

**Issue by ventralnet** [Jexordexan/vue-slicksort#131]
I believe this is probably because the 'ghost' element that shows when you are dragging is created from a cloneNode call.  canvas contexts aren't part of the DOM so they won't be cloned with this method.

Not a huge deal for me, but just thought I would log it for the record

**Comment by Jexordexan** [comment]
Yeah not much we can do about this, we have to clone the node so the original can stay in place.
