### ISSUE TITLE
vue3+vite2+tsx after dragging slice error

### ISSUE THREAD

**Issue by songjianet** [Jexordexan/vue-slicksort#132]
![image](https://user-images.githubusercontent.com/19239641/113407282-8dbe9680-93df-11eb-8f80-80a42814714f.png)
![image](https://user-images.githubusercontent.com/19239641/113407309-9b741c00-93df-11eb-866b-a472a10eb842.png)
![image](https://user-images.githubusercontent.com/19239641/113407325-a0d16680-93df-11eb-99f9-269e6a156a51.png)
https://github.com/songjianet/vue-questionare-generator-antd/blob/main/src/components/ranking/Ranking.tsx

**Comment by Jexordexan** [comment]
Hi, can you include the version of slicksort you are using and a reproduction repo/link?

I also noticed `v-model_list` is that the correct syntax for JSX?

**Comment by Jexordexan** [comment]
According to https://github.com/vuejs/jsx-next#directives You need a different syntax for v-model.

I think it should be:
```
v-model={[ options, 'list' ]}
```
