### ISSUE TITLE
Nested list - Collapse children items when dragging/dropping the parent

### ISSUE THREAD

**Issue by cedrus-8864** [Jexordexan/vue-slicksort#138]
As the title, I think it will be very helpful. 
A parent item has many children items. When dragging/dropping the parent, it's a little bit difficult to put it in the right position.

Thanks for your awesome work.

**Comment by Jexordexan** [comment]
Hey @cedrus-8864 I think this feature is a bit out of scope for the library. I encourage you to use the emitted events to achieve this. If there is an event you think should be emitted for you to do so, please open a new issue with details of when and what should be emitted. Thanks!
