### ISSUE TITLE
Update fiddle link

### ISSUE THREAD

**Issue by atilkan** [Jexordexan/vue-slicksort#16]
fiddle link is broken.

**Comment by Jexordexan** [comment]
I'll get a fix for that ASAP!

**Comment by atilkan** [comment]
Thanks. You could close when you fix, so i can get notification and you would not forget. :)

**Comment by Jexordexan** [comment]
Its fixed, and should be live at https://jsfiddle.net/Jexordexan/1puv2L6c/

**Comment by atilkan** [comment]
@Jexordexan Thanks. There is a mistake in the example. 
Correct usage should be for axis. **lock-axis="y"**

**Comment by atilkan** [comment]
Also **user-select: none;** for **li** elements would help unwanted selection problem.

**Comment by Jexordexan** [comment]
All have been updated! Thanks for pointing out the issues 😄
