### ISSUE TITLE
Clear Examples Required

### ISSUE THREAD

**Issue by atilkan** [Jexordexan/vue-slicksort#17]
The example is not descriptive. Others a bit complicated.
Where do you write this?
useDragHandle="true"
Can you provide separate examples?

**Comment by atilkan** [comment]
If i understand, i would help gladly. Thank you.

**Comment by rugor** [comment]
Bump on this... `useDragHandle="true"` not doing it for me.

https://jsfiddle.net/3jL184cg/2/

**Comment by atilkan** [comment]
You should use it like a binding with kebab-case

:use-drag-handle="true"

And you should include handlemixin. It frasturated me too. I will post clear example later if you need.

**Comment by rugor** [comment]
Went digging and found this: https://jsfiddle.net/djbwn27o/57/
Thanks @atilkan

**Comment by Jexordexan** [comment]
It should be noted that when using inline HTML templates like in jsfiddle, the standard prop syntax of camelCase is not valid. It is only valid in template strings and `.vue` templates

**Comment by atilkan** [comment]
@Jexordexan People generally don't read docs. So examples are always helpful.

**Comment by 2b0x** [comment]
> You should use it like a binding with kebab-case
> 
> :use-drag-handle="true"
> 
> And you should include handlemixin. It frasturated me too. I will post clear example later if you need.

hi~bro! i also cant understand how to use it, i had add the element ':use-drag-handle="true" ', but it not effect, did you pass the  problem, help~ (┬＿┬)

**Comment by 2b0x** [comment]
hibro! i also cant understand how to use it, i had add the element ':use-drag-handle="true" ', but it not effect, did you pass the problem, help (┬＿┬)
