### ISSUE TITLE
SCSS & SASS disappearing when sorting problem 

### ISSUE THREAD

**Issue by dstallenberg** [Jexordexan/vue-slicksort#27]
Hello Jexordexan,

Awesome project!
I found out that when you use SASS or SCSS for your markup, that slicksort won't be able to find the right css config. You kinda addressed this issue here:
"Item disappearing when sorting / CSS issues"
But I think this is worth noting.
So a quick example:

Template list: 
```
'<ul class="input-list"><slot /></ul>'
```
Template item: 
```
'<li class="draggable">{{item}}</li>'
```
SCSS: 
```
.input-list {
  .draggable {
    cursor: pointer;
  }
}
```

Now when dragging the newly made ```<li>```  will be in ```<body>``` and won't be able to find .draggable because it's nested.

This isn't really an issue but maybe it's worth telling users.

Greetings Dimitri

**Comment by Jexordexan** [comment]
I'm pretty sure the FAQ addresses this pretty explicitly

> If the sortable-helper gets messed up from a CSS standpoint, consider that maybe your selectors to the draggable item are dependent on a parent element which isn't present anymore (again, since the sortable-helper is at the end of the <body>)

**Comment by EMMMMMMMMMMMMM** [comment]
Hello, this problem has not been effectively solved. The corresponding SCSS cannot be found when dragging the mutated files under SCSS
