### ISSUE TITLE
Example that supports placeholders / gaps / blank spaces in a draggable list

### ISSUE THREAD

**Issue by u01jmg3** [Jexordexan/vue-slicksort#30]
Basically I'm trying to create something like this rather crude [jQuery UI example](https://jsfiddle.net/ali_soltani/6yo9djcb/1/).

- You can drag any of the words to a free gap in any order
- You can override a word with another (which returns the overridden word back to the pool)
- You can drag an allocated word back to the pool leaving the gap open as it was
- You can remove a word once it is allocated to a gap using the close button

I've looked at the examples, but it seems like they don't allow "blank" items to exist.

Does anyone know of an example that supports this, or have an idea how it can be achieved with this library?

**Comment by Jexordexan** [comment]
I think what you are asking for is a [standalone drop area component](https://github.com/Jexordexan/vue-slicksort/issues/5), which compels me to merge with #5.

**Comment by u01jmg3** [comment]
Agreed :)
