### ISSUE TITLE
TypeError: this.$el.sortableInfo is undefined

### ISSUE THREAD

**Issue by throskam** [Jexordexan/vue-slicksort#31]
Hello Jexordexan,

I have the following error when I prepend new items to a *SlickSort* list.

`TypeError: this.$el.sortableInfo is undefined`

The error occurs when the items in the list are **disabled** and their keys are not equal to their index.
Otherwise it works fine.

Here is a jsFiddle that showcase the error: https://jsfiddle.net/spoutnik/7nqm1L56/
Just prepend a new item and look at the console.

I don't really know why but I'm guessing it's due to how Vue is optimizing list rendering when the key is more closely linked to the item itself.

When you trace the error down, you reach this line https://github.com/Jexordexan/vue-slicksort/blob/master/src/ElementMixin.js#L30

Cheers,

**Comment by Jexordexan** [comment]
Thanks for finding this, I think its because of https://github.com/Jexordexan/vue-slicksort/blob/b8b627bf97c296d7da923e724c50596bd7d957e4/src/ElementMixin.js#L49

It only initializes the data if disabled is false.

**Comment by throskam** [comment]
Yeah, but it makes sense to avoid initializing disabled element.
I think it would be better to just change the condition in the index watcher: 

`if (this.$el && this.$el.sortableInfo)` 

or 

`if (this.$el && !this.disabled)` (if `disabled` is strongly linked to the present of `sortableInfo`)

What do you think ?
I could make a PR if you want ?
