### ISSUE TITLE
What conditions trigger the slip of the previous or next element when dragging up or dragging down

### ISSUE THREAD

**Issue by lizhentong** [Jexordexan/vue-slicksort#34]
Hello Jexordexan,

What conditions trigger the slip of the previous or next element when dragging up or dragging down?When my sorting elements are not the same height, it is sometimes difficult to trigger the sorting of the elements. Is there a way to set the sorting of the element by dragging the dragged element up or down by 50px?

thanks.

**Comment by Jexordexan** [comment]
Duplicate of #32
