### ISSUE TITLE
[help] v-handle inside component

### ISSUE THREAD

**Issue by atilkan** [Jexordexan/vue-slicksort#36]
How can i use v-handle inside mixin component?

**Forex:**
I pass custom component in mixin.

```
let SortableItem = { 
mixins: [ElementMixin], 
props: ["item"], 
directives: { handle: HandleDirective }, 
template: '<question-shell v-bind:question="'What is your name?'" question-type="paragraph" v-bind:question-no="1"></question-shell>', }
```
This is inside component.

```
<div class="handle" v-handle>
    <div class="icon-alpha size-32"></div>
</div>
```

How can i  use **v-hande** directive inside another component?

**Comment by atilkan** [comment]
@Jexordexan.  I tried doing slots but maybe there is cleaner way.

**Comment by Jexordexan** [comment]
You need to use the `v-handle` in the template for the same component it is registered.

To make the handle directive usable anywhere, you can use `Vue.directive('handle', HandleDirective)` wherever you initialize vue.

**Comment by atilkan** [comment]
@Jexordexan Sorry, i don't understand. Can you point me an example?

**Comment by atilkan** [comment]
I ended up using slots.

**Comment by mattbishop** [comment]
@Jexordexan it would be helpful to put the `Vue.directive('handle', HandleDirective)` line in the README examples in HandleDirective. the `export` one doesn't work with `SlickItem` but the explicit directive registration works as expected.
