### ISSUE TITLE
Standalone Slicksort component

### ISSUE THREAD

**Issue by Jexordexan** [Jexordexan/vue-slicksort#4]
This could behave similarly to the `<draggable>` component in [vuedraggable](https://github.com/SortableJS/Vue.Draggable) Where there is one component with a slot for it's children, which have been iterated using `v-for`.

**Comment by eyy** [comment]
Another option is to export two components, matching the two mixins. That's what I'm using:
```
import { ContainerMixin, ElementMixin } from 'vue-slicksort'

const SortableList = {
  mixins: [ ContainerMixin ],
  template: '<div><slot /></div>'
}

const SortableItem = {
  mixins: [ ElementMixin ],
  template: '<div><slot /></div>'
}
```

**Comment by atilkan** [comment]
@eyy how do you pass options. For example useDragHandle="true".

**Comment by eyy** [comment]
It's a mixin, the options are passed automatically:

```html
<sortable-list
      v-model="here"
      lockAxis="y"
      :useDragHandle="true"
    >
      <sortable-item
        v-for="(doc, index) in here"
        :index="index"
        :key="doc._id"
        class="box"
      >
// etc.
```

**Comment by atilkan** [comment]
@eyy Thank you. These should be on docs.

**Comment by atilkan** [comment]
@eyy BTW. The correct usage should be **:use-drag-handle="true"**

**Comment by eyy** [comment]
Perhaps these minimal components can be included in the library?

**Comment by Jexordexan** [comment]
My hesitation about including those is that at some point I want a singular component to do everything kind of like [vue-draggable](https://github.com/SortableJS/Vue.Draggable). I dont want people to be confused about which component to use, and when.

**Comment by eyy** [comment]
I think it's clearer that there are two components; The right naming, and a simple example in the README file, can go a long way.

**Comment by Jexordexan** [comment]
Hmm, okay! Thanks for your input :) I guess two components isn't terrible and it doesn't require much more code. If you could make a PR and prioritize `render` functions, that'd be great!

**Comment by eyy** [comment]
:) Will do.
What do you mean by prioritize `render` functions?

**Comment by Jexordexan** [comment]
Don't use the `template` string as it is not compatible with the runtime version of vue. Better to use a `render` function instead!

More info:
https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only
