### ISSUE TITLE
Is it possible to drag an object from one nested list to another?

### ISSUE THREAD

**Issue by dleast** [Jexordexan/vue-slicksort#42]
Hi,

Is it possible to drag an object from one nested list to another nested list as indicated by the attached image? It is not doable on the demo page. Thank you for a great component!
![2018-08-15_10-04-38](https://user-images.githubusercontent.com/4190573/44138147-4a94ab04-a073-11e8-8de7-f5728c270aa5.png)

**Comment by junhengDeng** [comment]
+1

**Comment by Jexordexan** [comment]
Merge with #13
