### ISSUE TITLE
report error when i use  v-handle 

### ISSUE THREAD

**Issue by liujiangfeng** [Jexordexan/vue-slicksort#46]
[Vue warn]: Injection "manager" not found

found in

---> <BatchMgr> at src/pages/choose/batchMgr.vue
       <Choose> at src/pages/choose/index.vue
         <App> at src/App.vue
           <Root>

 [Vue warn]: Missing required prop: "index"

found in

---> <BatchMgr> at src/pages/choose/batchMgr.vue
       <Choose> at src/pages/choose/index.vue
         <App> at src/App.vue
           <Root>

raven.min.js:2 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'add' of undefined"

found in

---> <BatchMgr> at src/pages/choose/batchMgr.vue
       <Choose> at src/pages/choose/index.vue
         <App> at src/App.vue
           <Root>a.(anonymous function) 
 TypeError: Cannot read property 'add' of undefined(…)

**Comment by liujiangfeng** [comment]
close

**Comment by OverlappingElvis** [comment]
@liujiangfeng were you able to resolve this? I'm seeing the same thing, although the plugin appears to be working

**Comment by cwist2** [comment]
@liujiangfeng Any news ?
