### ISSUE TITLE
Please update npm packet

### ISSUE THREAD

**Issue by bruian** [Jexordexan/vue-slicksort#67]
the last packet isn't having bugfix which is contained in issue [#61](https://github.com/Jexordexan/vue-slicksort/pull/61)

**Comment by samuil4** [comment]
Hi, I'm also looking for the next update of the package.

**Comment by atanasr** [comment]
+1 for updating the npm package.

**Comment by preterer** [comment]
It's been updated 9 hours ago so I think this issue can be closed @Jexordexan

**Comment by preterer** [comment]
@Jexordexan problem is the npm package update includes this commit https://github.com/Jexordexan/vue-slicksort/commit/3c47fb494eac51b1e784ab9d15174356c80dc892 which breaks the plugin, because you don't have babel-polyfill included. Working on a fix right now

**Comment by Jexordexan** [comment]
Package is up to date now 👍
