### ISSUE TITLE
Problem with useDragHandle=true 

### ISSUE THREAD

**Issue by 2b0x** [Jexordexan/vue-slicksort#79]
i want to show DragHandle but it not effect , its my code
`
<SlickList lockAxis="y" :useDragHandle="true" v-model="items" helperClass="stylizedHelper">
 <SlickItem  v-for="(item, index) in items" :index="index" :key="index" class="cityItem">
  {{ item }}
  </SlickItem>
 </SlickList>
`

`components: {SlickItem, SlickList},data() { return { items: ['item1', 'item2'], test: true  }; }`

i cant understand how to use it,  i think examples are always helpful
who guy can help me, thank u~ (┬＿┬)

**Comment by Jexordexan** [comment]
You have to couple the useDragHandle with a `v-handle` in the items. There's an example in the readme: https://github.com/Jexordexan/vue-slicksort#handledirective
