### ISSUE TITLE
Apply without separating components?

### ISSUE THREAD

**Issue by syropian** [Jexordexan/vue-slicksort#8]
I currently have something (slightly simplified) like this:

```html
<ul class="sidebar-list">
  <sidebar-item 
    v-for="tag in sortedTags" 
    :key="tag.id" 
    :class="{ 'selected': currentTag.id == tag.id }"
    >
    </sidebar-item>
</ul>
```

Is there an easy way for me to apply the mixins without breaking each bit into another component? The `sidebar-item` component isn't always in a sortable container in this case, but I don't want to have to duplicate the component just to apply the mixin to it, while not applying it to others.

**Comment by Jexordexan** [comment]
As it is currently implemented, you have to use a mixin for both parent and children. #4 will hopefully make using this library simpler.
