### ISSUE TITLE
Can i sync scroll 2 components in vue-slicksort

### ISSUE THREAD

**Issue by teerapat1739** [Jexordexan/vue-slicksort#86]

**Comment by 2mod** [comment]
what do u mean with sync scroll? please give an example

**Comment by teerapat1739** [comment]
Now, i got it.
https://www.finnomena.com/fund/compare?fund=M-PROP%20RMF,M-PROP%20DIV,T-PropInfraFlex,PRINCIPAL%20iPROP-A
