### ISSUE TITLE
Text being selected on drag [Firefox]

### ISSUE THREAD

**Issue by johnfraney** [Jexordexan/vue-slicksort#9]
I've noticed that when using Firefox, text is getting selected when an item is dragged over top of one or more other items. It seems to be that this happens if the initial click is in the text portion of an element (but not if the initial click is in the padding or margin).

![slicksort-firefox-text-selection](https://user-images.githubusercontent.com/1728528/36080110-909b67ee-0f61-11e8-953a-436fd56823a4.gif)

**Comment by johnfraney** [comment]
I did some more digging into this. The example items have a `user-select: none;` CSS attribute applied, which Chrome is picking up but Firefox isn't. Adding [vendor-specific prefixes](https://stackoverflow.com/a/14307806/3930128) for `user-select` fixes this:
```
{
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

**Comment by Jexordexan** [comment]
Good call @johnfraney, I'll push an update to the CSS! I also seem to recall being able to avoid text highlighting with a special combo of `event.preventDefault()`. I think I might be able to prevent this on the javascript end so you don't have to add `user-select: none` to your own CSS and possibly prevent people from highlighting when they actually want to.

**Comment by johnfraney** [comment]
@Jexordexan I'm noticing now in version 0.1.5 that items with the `ElementMixin` no longer register click events. Maybe the CSS fix is the safer option.
